version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:9


jobs:

  test:
    <<: *defaults
    steps:
      - checkout
      - run: yarn
      - run: node_modules/.bin/greenkeeper-lockfile-update
      - run: make spec
      - run: node_modules/.bin/greenkeeper-lockfile-upload

  deploy:
    <<: *defaults
    steps:
      - checkout
      - run: yarn
      - run: make build
      - run: npm set //registry.npmjs.org/:_authToken $AUTH_TOKEN
      - run: npm publish

workflows:
  version: 2

  test:
    jobs:
      - test

  deploy:
    jobs:
      - deploy:
          filters:
            tags:
              only: /^v.*/
