version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:10

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          name: restore Yarn cache
          keys:
            - yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-{{ .Branch }}
            - yarn-master
            - yarn-
      - run: yarn
      - run: make lint
      - run: make coverage
      - save_cache:
          name: save Yarn cache
          key: yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/
  deploy:
    <<: *defaults
    steps:
      - checkout
      - run: yarn
      - run: make build
      - run: npm set //registry.npmjs.org/:_authToken $AUTH_TOKEN
      - run: npm publish

workflows:
  version: 2
  pr:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
  deploy:
    jobs:
      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /^v.*/
